rnn_size: 650
num_layers: 2
input_keep_prob: 0.5
intra_keep_prob: 0.5
state_keep_prob: 1.0
output_keep_prob: 0.5
batch_size: 20
timesteps: 35
grad_clip: 5.0
lr: 0.001
lr_decay: 0.9
eval_freq: 2000000
decay_after: 5
num_epochs: 50
margin_ppl: 1
shared_embeddings: True
optimizer: adam